# Default values for nova-api-proxy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

labels:
  api_proxy:
    node_selector_key: openstack-control-plane
    node_selector_value: enabled
  job:
    node_selector_key: openstack-control-plane
    node_selector_value: enabled 

images:
  tags:
      nova_api_proxy: 128.224.186.231:9001/abailey/stx-nova-api-proxy:latest
      ks_endpoints: docker.io/openstackhelm/heat:newton
      dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.3.1
  pullPolicy: IfNotPresent
  local_registry:
    active: false
    exclude:
      - dep_check
      - image_repo_sync

network:
  api_proxy:
    ingress:
      public: true
      classes:
        namespace: "nginx"
        cluster: "nginx-cluster"
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
    external_policy_local: false
    node_port:
      enabled: false
      port: 8774

conf:
  nova_api_proxy:
    DEFAULT:
      log_config_append: /etc/proxy/logging.conf
      api_paste_config: api-proxy-paste.ini
      auth_strategy: keystone
      debug: False
      use_syslog: False
      show_request_body: False
      pool_size: 256
      osapi_proxy_listen: 0.0.0.0
      osapi_proxy_listen_port: 8774
      osapi_compute_listen: nova-api.openstack.svc.cluster.local
      osapi_compute_listen_port: 8774
      nfvi_compute_listen_port: 30003
      nfvi_compute_listen: 0.0.0.0
    keystone_authtoken:
      auth_type: password
      auth_version: v3

  paste:
    pipeline:nova-api-proxy:
      pipeline: version authtoken acceptor proxyapp
    filter:debug_header:
      paste.filter_factory: nova_api_proxy.apps.acceptor:DebugHeaders.factory
    filter:version:
      paste.filter_factory: nova_api_proxy.apps.acceptor:VersionAcceptor.factory
    filter:authtoken:
      paste.filter_factory: keystonemiddleware.auth_token:filter_factory
    filter:acceptor:
      paste.filter_factory: nova_api_proxy.apps.acceptor:Acceptor.factory
    app:proxyapp:
      paste.app_factory: nova_api_proxy.apps.proxy:Proxy.factory

  logging:
    loggers:
      keys:
        - root
        - nova_api_proxy
        - keystonemiddleware
    handlers:
      keys:
        - stdout
        - stderr
        - "null"
    formatters:
      keys:
        - context
        - default
    logger_root:
      level: WARNING
      handlers: null
    logger_nova_api_proxy:
      level: INFO
      handlers:
        - stdout
      qualname: nova_api_proxy
    logger_keystonemiddleware:
      level: INFO
      handlers:
        - stdout
      qualname: keystonemiddleware
    logger_amqp:
      level: WARNING
      handlers: stderr
      qualname: amqp
    logger_amqplib:
      level: WARNING
      handlers: stderr
      qualname: amqplib
    logger_eventletwsgi:
      level: WARNING
      handlers: stderr
      qualname: eventlet.wsgi.server
    logger_sqlalchemy:
      level: WARNING
      handlers: stderr
      qualname: sqlalchemy
    logger_boto:
      level: WARNING
      handlers: stderr
      qualname: boto
    handler_null:
      class: logging.NullHandler
      formatter: default
      args: ()
    handler_stdout:
      class: StreamHandler
      args: (sys.stdout,)
      formatter: context
    handler_stderr:
      class: StreamHandler
      args: (sys.stderr,)
      formatter: context
    formatter_context:
      class: oslo_log.formatters.ContextFormatter
    formatter_default:
      format: "%(message)s"

dependencies:
  dynamic:
    common:
      local_image_registry:
        jobs:
          - image-repo-sync
        services:
          - endpoint: node
            service: local_image_registry
  static:
    ks_endpoints:
      jobs:
        - nova-ks-service
      services:
        - endpoint: internal
          service: identity


endpoints:
  cluster_domain_suffix: cluster.local
  local_image_registry:
    name: docker-registry
    namespace: docker-registry
    hosts:
      default: localhost
      internal: docker-registry
      node: localhost
    host_fqdn_override:
      default: null
    port:
      registry:
        node: 5000
  identity:
    name: keystone
    auth:
      admin:
        region_name: RegionOne
        username: admin
        password: password
        project_name: admin
        user_domain_name: default
        project_domain_name: default
      nova:
        role: admin
        region_name: RegionOne
        username: nova
        password: password
        project_name: service
        user_domain_name: service
        project_domain_name: service
    hosts:
      default: keystone-api
      public: keystone
    host_fqdn_override:
      default: null
    path:
      default: /v3
    scheme:
      default: http
    port:
      admin:
        default: 35357
      api:
        default: 80
  compute:
    name: nova
    hosts:
      default: nova-api-proxy
      public: nova-api-proxy
    host_fqdn_override:
      default: null
      # NOTE(portdirect): this chart supports TLS for fqdn over-ridden public
      # endpoints using the following format:
      # public:
      #   host: null
      #   tls:
      #     crt: null
      #     key: null
    path:
      default: "/v2.1/%(tenant_id)s"
    scheme:
      default: 'http'
    port:
      api:
        default: 8774
        public: 80

pod:
  user:
    nova_api_proxy:
      uid: 42424
  affinity:
    anti:
      type:
        default: preferredDuringSchedulingIgnoredDuringExecution
      topologyKey:
        default: kubernetes.io/hostname
  mounts:
    nova_api_proxy:
      init_container: null
      nova_api_proxy:
  replicas:
    proxy: 1
  lifecycle:
    upgrades:
      deployments:
        revision_history: 3
        pod_replacement_strategy: RollingUpdate
        rolling_update:
          max_unavailable: 1
          max_surge: 3
      daemonsets:
        pod_replacement_strategy: RollingUpdate
        compute:
          enabled: true
          min_ready_seconds: 0
          max_unavailable: 1
    disruption_budget:
      api_proxy:
        min_available: 0
    termination_grace_period:
      api_proxy:
        timeout: 30
  resources:
    enabled: false
    api_proxy:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "1024Mi"
        cpu: "2000m"
    jobs:
      ks_endpoints:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "1024Mi"
          cpu: "2000m"

secrets:
  identity:
    admin: nova-keystone-admin
    nova: nova-keystone-user


manifests:
  configmap_bin: true
  configmap_etc: true
  deployment_api_proxy: true
  ingress_api: true
  job_ks_endpoints: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
