#
# SPDX-License-Identifier: Apache-2.0
#

# Default values for fm-rest-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: starlingx/stx-fm-rest-api
  tag: dev-centos-pike-build
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 18003

ingress:
  enabled: false
  annotations: {}
  paths: []
  hosts:
    - fm-rest-api
  tls: []

conf:
  paste:
    app:api_v1:
      paste.app_factory: fm.api.app:app_factory
    filter:authtoken:
      acl_public_routes: /, /v1
      paste.filter_factory: fm.api.middleware.auth_token:AuthTokenMiddleware.factory
    filter:request_id:
      paste.filter_factory: oslo_middleware:RequestId.factory
    pipeline:fm-api:
      pipeline: request_id authtoken api_v1

  fm:
    DEFAULT:
      use_syslog: True
      syslog_log_facility: local2
      trap_destinations:
      region_name: RegionOne
      event_log_max_size: 4000
    database:
      idle_timeout: 60
      max_pool_size: 1
      max_overflow: 20
    oslo_middleware:
      enable_proxy_headers_parsing: True
    keystone_authtoken:
      user_domain_name: Default
      project_name: services
      auth_type: password
      username: fm
      region_name: RegionOne
      project_domain_name: Default
      password: password
    sysinv:
      catalog_info: platform:sysinv:internalURL
      os_region_name: RegionOne
    api:
      api_paste_config: /etc/fm/api-paste.ini
      api_workers: 2
      bind_port: 18003

manifests:
  configmap_bin: true
  configmap_etc: true

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
