#!/bin/bash
# Devstack settings

# Defaults
# --------

STX_CONFIG_NAME=stx-config

######### Plugin Specific ##########
enable_service $STX_CONFIG_NAME sysinv sysinv-api sysinv-cond
#define_plugin sysinv

# Handle STX pre-reqs
enable_service tsconfig

# Initial source of lib script
source $DEST/stx-config/devstack/lib/stx-config
