# Copyright 2017 The Openstack-Helm Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Default values for garbd.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

conf:
  garbd:
    group_name: mariadb-server_openstack
    group_address: gcomm://mariadb-server-0.mariadb-discovery.openstack.svc.cluster.local,mariadb-server-1.mariadb-discovery.openstack.svc.cluster.local 

dependencies:
  dynamic:
    common:
      local_image_registry:
        jobs:
          - garbd-image-repo-sync
        services:
          - endpoint: node
            service: local_image_registry
  static:
    image_repo_sync:
      services:
        - endpoint: internal
          service: local_image_registry

endpoints:
  cluster_domain_suffix: cluster.local
  local_image_registry:
    name: docker-registry
    namespace: docker-registry
    hosts:
      default: localhost
      internal: docker-registry
      node: localhost
    host_fqdn_override:
      default: null
    port:
      registry:
        node: 5000
  kube_dns:
    namespace: kube-system
    name: kubernetes-dns
    hosts:
      default: kube-dns
    host_fqdn_override:
      default: null
    path:
      default: null
    scheme: http
    port:
      dns_tcp:
        default: 53
      dns:
        default: 53
        protocol: UDP

network_policy:
  garbd:
    ingress:
      - {}

images:
  pull_policy: IfNotPresent
  tags:
    dep_check: 'quay.io/stackanetes/kubernetes-entrypoint:v0.3.1'
    garbd: 'docker.io/starlingx/stx-mariadb:dev-centos-pike-latest'
    image_repo_sync: docker.io/docker:17.07.0
  local_registry:
    active: false
    exclude:
      - image_repo_sync

labels:
  server:
    node_selector_key: openstack-compute-node
    node_selector_value: enabled

manifests:
  configmap_bin: true
  deployment: true

pod:
  affinity:
    anti:
      topologyKey:
        default: kubernetes.io/hostname
      type:
        default: preferredDuringSchedulingIgnoredDuringExecution
  lifecycle:
    upgrades:
      deployments:
        pod_replacement_strategy: RollingUpdate
        revision_history: 3
        rolling_update:
          max_surge: 3
          max_unavailable: 1
    termination_grace_period:
      garbd:
        timeout: 10
  replicas:
    server: 1
  resources:
    enabled: false
    garbd:
      limits:
        cpu: "2000m"
        memory: "1024Mi"
      requests:
        cpu: "500m"
        memory: "128Mi"
