{{/*
#
#Copyright (c) 2018 Wind River Systems, Inc.
#
#SPDX-License-Identifier: Apache-2.0
#
*/}}

{{- if .Values.manifests.secret_ingress_tls }}
{{ include "helm-toolkit.manifests.secret_ingress_tls" ( dict "envAll" . "backendService" "osapi" "backendServiceType" "compute" ) }}
{{- end }}
